<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.github.rebue.wheel</groupId>
        <artifactId>wheel-kafka</artifactId>
        <version>3.7.57</version>
    </parent>

    <artifactId>connector-tests</artifactId>
    <packaging>jar</packaging>
    <name>connector-tests</name>
    <description>Kafka 连接器的测试</description>

    <dependencies>
        <dependency>
            <artifactId>jakarta.ws.rs-api</artifactId>
            <groupId>jakarta.ws.rs</groupId>
            <version>4.0.0</version>
            <scope>test</scope>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>javax.ws.rs</groupId>-->
<!--            <artifactId>javax.ws.rs-api</artifactId>-->
<!--            <version>2.0</version>-->
<!--            <scope>test</scope>-->
<!--        </dependency>-->
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-http</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-util</artifactId>
            <version>9.4.56.v20240826</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-io</artifactId>
            <version>9.4.56.v20240826</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>4.0.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-client</artifactId>
            <version>9.4.56.v20240826</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-server</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>connect-runtime</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
            <exclusions>
<!--                <exclusion>-->
<!--                    <artifactId>javax.ws.rs-api</artifactId>-->
<!--                    <groupId>javax.ws.rs</groupId>-->
<!--                </exclusion>-->
                <exclusion>
                    <artifactId>jersey-container-servlet</artifactId>
                    <groupId>org.glassfish.jersey.containers</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>jakarta.ws.rs-api</artifactId>
                    <groupId>jakarta.ws.rs</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
    </dependencies>
</project>
