package rebue.wheel.core;

public class LombokUtils {
    /**
     * Removes the null values from String generated through the @ToString annotation.
     * For example:
     * - replaces: AddressEntity(id=null, adrType=null, adrStreet=null, adrStreetNum=null, adrComplement=null, adrPoBox=null, adrNip=null, adrCity=city, adrCountry=null,
     * adrNameCorresp=nameCorresp, adrSexCorresp=null, adrSource=null, adrSelectionReason=null, validityBegin=null, validityEnd=null, lastModification=null, dataQuality=null)
     * - by: AddressEntity(adrCity=city, adrNameCorresp=nameCorresp)
     * Note: does not support tricky attribute content such as "when, x=null, it fails".
     *
     * @param lombokToString a String generated by Lombok's @ToString method
     *
     * @return a string without null values
     */
    public static String removeToStringNullValues(final String lombokToString) {
        // Pattern
        return lombokToString != null ? lombokToString
                .replaceAll("(?<=(, |\\())[^\\s(]+?=null(?:, )?", "")
                .replaceFirst(", \\)$", ")") : null;
    }
}
