<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.github.rebue.wheel</groupId>
        <artifactId>wheel</artifactId>
        <version>3.8.59</version>
    </parent>

    <artifactId>wheel-kafka</artifactId>
    <packaging>pom</packaging>
    <name>wheel-kafka</name>
    <description>Kafka 的工具库</description>
    <modules>
        <module>http-sink-connector</module>
        <module>connector-tests</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <wheel.version>3.8.59</wheel.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.github.rebue.wheel</groupId>
                <artifactId>wheel</artifactId>
                <version>${wheel.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
